.PHONY: clean All

All:
	@echo "----------Building project:[ testcpp - Debug ]----------"
	@$(MAKE) -f  "testcpp.mk"
clean:
	@echo "----------Cleaning project:[ testcpp - Debug ]----------"
	@$(MAKE) -f  "testcpp.mk" clean
